[package]
name = "mahf-tsplib"
version = "0.1.0"
edition = "2021"

[dependencies]
mahf = { git = "https://github.com/mahf-opt/mahf" }

tspf = "0.3.1"
include_dir = "0.7.3"
strum = { version = "0.24.1", features = ["derive"] }
